[".local/share/nvim/site/pack/plugins/start/lightline"]
    type = "archive"
    url = "https://github.com/itchyny/lightline.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

# Neovim theme: dracula
[".local/share/nvim/site/pack/themes/start/dracula"]
    type = "archive"
    url = "https://github.com/dracula/vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

# Yazi theme: dracula
[".config/yazi/flavors/dracula.yazi"]
    type = "archive"
    url = "https://github.com/dracula/yazi/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/fish/completions/eza.fish"]
    type = "file"
    url = "https://raw.githubusercontent.com/eza-community/eza/main/completions/fish/eza.fish"
    refreshPeriod = "168h"

[".config/fish/completions/dust.fish"]
    type = "file"
    url = "https://raw.githubusercontent.com/bootandy/dust/refs/heads/master/completions/dust.fish"
    refreshPeriod = "168h"

# Zellij theme: dracula
[".config/zellij/themes"]
    type = "archive"
    url = "https://github.com/dracula/zellij/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"