# BEGIN_KITTY_THEME
# Dracula
include dracula.conf
# END_KITTY_THEME

# Window appearance
window_padding_width 2
single_window_padding_width 2

# Transparency and blur
background_opacity 0.9
dynamic_background_opacity yes
background_blur 3

font_size 14.0

# Fonts - using modern extended syntax
font_family      Monaspace Neon NF

disable_ligatures cursor