[tools]
pnpm = "latest"
uv = "latest"
python = "latest"
node = "latest"
go = "latest"

eza = "latest"
dust = "latest"
fd = "latest"
bottom = "latest"
bat = "latest"
ripgrep = "latest"
zoxide = "latest"
fzf = "latest"
duf = "latest"
yazi = "latest"
tokei = "latest"
ffmpeg = "latest"
tmux = "latest"
neovim = "latest"
jq = "latest"
tlrc = "latest"

[env]
_.file = '~/.config/mise/.env'